#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

mkdir -p build

# IMPORTANT(Ryan): Must compile with gcc as oppose to as to use the cpp
arm-none-eabi-gcc -ffreestanding -nostdlib -x assembler-with-cpp -Wl,-eentry -g \
  -mcpu=cortex-a7 code/ras.s -o build/ras.elf

arm-none-eabi-objcopy build/ras.elf -O binary build/kernel7.img
