#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

mkdir -p build

arm-none-eabi-as -g code/ras.s -o build/ras.o
# NOTE(Ryan): Inspect .text address with '--verbose' 
arm-none-eabi-ld -e entry build/ras.o -o build/ras.elf

arm-none-eabi-objcopy build/ras.elf -O binary build/kernel7.img
